# Generated by Django 4.0.4 on 2022-05-31 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, help_text='48px X 48px 크기의 png/jpg 파일을 업로드해주세요', upload_to='accounts/profile/%Y/%m/%d'),
        ),
    ]
