# Generated by Django 4.0.4 on 2022-05-31 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(upload_to='posting/post/%Y/%m/%d'),
        ),
    ]
